version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: brickbase-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brickbase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - brickbase-network

  redis:
    image: redis:alpine
    container_name: brickbase-redis
    ports:
      - "6379:6379"
    networks:
      - brickbase-network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

networks:
  brickbase-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 